### ISSUE TITLE
Error on save

### ISSUE THREAD

**Issue by proweb** [HexRx/simple-ftp-deploy#1]
Installed in Sublime 3

On save have error in console:
`ftplib.error_perm: 550 Failed to change directory`

![image](https://cloud.githubusercontent.com/assets/680073/8508622/3b023482-2280-11e5-832c-6817da32c753.png)

How to solve it?

**Comment by Aiq0** [comment]
Maybe so late, but if someone will have same error, I'll probably help. The issue is, that folder you are trying to upload to doesn't exists. Check if you set up root folder correctly (if you are not uploading to root). Since #5, you'll be prompted, if you want to create directory (or it'll be done automatically, when "autoCreateDirectory" is set to true).
