### ISSUE TITLE
Problem with creating subfolders

### ISSUE THREAD

**Issue by urtvs** [HexRx/simple-ftp-deploy#17]
![image](https://user-images.githubusercontent.com/57058864/147433953-2de0c423-6359-46a9-8fd4-7efb929f5e32.png)

I find in sublime text 3 + simple ftp deploy such problem

When i create inside existing folder + file in this folder - its deploy!
When i created nested folders new folder1/folder2/file.txt - its cant deploy

Is it possible to fixed?

PS: Also strange thank i setup not to confirm for creating folders - but it always ask me
“noPromptEvents”: [“createFolder”],

[Simple FTP Deploy] [Connected 07:22:14]: HOST:21 (2112ms)
Traceback (most recent call last):
File “C:\Program Files\Sublime Text 3\Lib\python33\sublime_plugin.py”, line 908, in on_post_save_async
run_view_callbacks(‘on_post_save_async’, view_id)
File “C:\Program Files\Sublime Text 3\Lib\python33\sublime_plugin.py”, line 708, in run_view_callbacks
callback(v, *args)
File “C:\Program Files\Sublime Text 3\Lib\python33\sublime_plugin.py”, line 190, in exception_handler
return event_handler(*args)
File “C:\Users\vs\AppData\Roaming\Sublime Text 3\Installed Packages\Simple FTP Deploy.sublime-package\main.py”, line 304, in on_post_save_async
ftp.upload(folder, filename)
File “C:\Users\vs\AppData\Roaming\Sublime Text 3\Installed Packages\Simple FTP Deploy.sublime-package\main.py”, line 221, in upload
if not self.cdRecursivelly(fullFtpPath, prompt = not ‘createDirectory’ in self.config.get(‘noPromptEvents’, [])):
File “C:\Users\vs\AppData\Roaming\Sublime Text 3\Installed Packages\Simple FTP Deploy.sublime-package\main.py”, line 133, in cdRecursivelly
self.session.mkd(directory)
File “./python3.3/ftplib.py”, line 612, in mkd
File “./python3.3/ftplib.py”, line 269, in voidcmd
File “./python3.3/ftplib.py”, line 243, in voidresp
File “./python3.3/ftplib.py”, line 238, in getresp
ftplib.error_perm: 550

**Comment by Aiq0** [comment]
I'll look into it

**Comment by Aiq0** [comment]
Okay, it should be fixed in [my fork](https://github.com/Aiq0/simple-ftp-deploy) and in this repository with #16 merged. @urtvs can you please try my fork, if it works correctly?

P.S.: my bad, I used `"createFolder"` in README and `"createDirectory"` in code, now both should be accepted. To fix that before #16 gets merged, just use `"createDirectory"` instead of `"createFolder"` in `"noPromptEvents"`

**Comment by urtvs** [comment]
Hi!

I change in config to createDirectory and confirm for creating folder disabled!
But when i create folder + subfolder in one time(with out existing file in folder) its return error

ftplib.error_perm: 550 /www//b24/static/js/module/user/user/userStatus: ÐÐµÑ ÑÐ°ÐºÐ¾Ð³Ð¾ ÑÐ°Ð¹Ð»Ð° Ð¸Ð»Ð¸ ÐºÐ°ÑÐ°Ð»Ð¾Ð³Ð°
Package Control: No updated packages

I dont now how to install your update from fork? can you help me?

**Comment by Aiq0** [comment]
@urtvs uninstall package from package control (Command palette → Package control: Remove package), then [download](https://github.com/Aiq0/simple-ftp-deploy/archive/refs/heads/master.zip) package from [my fork](https://github.com/Aiq0/simple-ftp-deploy) and extract it to packages folder (from menu: Preferences → Browse Packages), so that in Packages folder will be folder simple-ftp-deploy (or any name of your choice), in which, there will be some files (`main.py`, `README.md`, ...)

P.S.: After @HexRx will merge #16 and will create release, please delete that extracted folder and install this package using package control, so you get all other updates...

P.P.S.: Please let me know, if everything works

**Comment by HexRx** [comment]
@urtvs hello, I've created a new release [1.7.0](https://github.com/HexRx/simple-ftp-deploy/releases/tag/1.7.0) which should fix this issue.
