### ISSUE TITLE
Password prompt

### ISSUE THREAD

**Issue by ringh0f** [HexRx/simple-ftp-deploy#18]
Hi,
i am not so comfortable with writing down certain passwords to customers ftp
servers in a text file. Is there a way to enter the the password on first upload on
an active/open sublime text project?

**Comment by Aiq0** [comment]
I can look into it when I get home, but it shouldn't be hard to implement. I will try to do a pull request

**Comment by Aiq0** [comment]
Ok, so it seems that we could use [`window.show_input_panel`](https://www.sublimetext.com/docs/api_reference.html#sublime.Window.show_input_panel) which will result in this:

![image](https://user-images.githubusercontent.com/66842415/194065248-d45006b8-9159-48df-8aa0-dcc84fe31394.png)

@ringh0f @HexRx if you are OK with this, I can implement it, so that if config file will miss password, then it will ask for password and if it will be correct, it will be saved along with host, port and user in memory, so it would be reused until Sublime Text will be closed. (or don't save it, just log in and use cached FTP session and if it expires, ask for password again?)

**Comment by ringh0f** [comment]
Sounds great for me, just what i hoped for.

**Comment by Aiq0** [comment]
Ok, I will try to implement it

**Comment by Aiq0** [comment]
@ringh0f I implemented it in [my fork](https://github.com/Aiq0/simple-ftp-deploy), can you please check it, if it works by temporarily uninstalling plugin from Package control and installing it manually from my fork ([instructions](https://github.com/HexRx/simple-ftp-deploy/issues/17#issuecomment-1010076872)) until it gets merged in #19 by @HexRx?

**Comment by ringh0f** [comment]
Great! I‘ll be able to try it tomorrow.

**Comment by HexRx** [comment]
@Aiq0 yup it sounds good :+1: Thank you for this feature, I'm going to merge it :rocket:
